### ISSUE TITLE
除了支持[]byte，希望增加对[]uint16等常见类型的支持

### ISSUE THREAD

**Issue by sohoer1997** [fananchong/go-redis-orm.v2#1]
除了支持[]byte，希望增加对[]uint16等常见类型的支持

**Comment by fananchong** [comment]
已支持。
版本 a3811518abd13ab4a0463b93dfd5c2451fdc6c92 ：类型11，支持结构体字段
版本 2fa972beef120e0a6b08d9dc24db00daeb03fc8e ：类型1n，支持结构体字段

目前支持 golang 基本数据类型以及 cstruct-go 能支持的所有类型
并去除原先支持的 int uint（未定义字节大小，因此不再支持）

1对N的数据，原先使用 json 做序列化，均改成了使用 ctruct-go 做序列化。因此本次修改不兼容旧的1对N数据。

**Comment by fananchong** [comment]
目前暂时支持 cstruct-go 序列化 struct obj。
很快将推出可制定 cstruct-go 、 json 、 protobufbuf  序列化 struct obj。
本 issue，关闭之
